# Generated by Django 4.1.10 on 2023-08-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
