# Generated by Django 4.1.10 on 2023-09-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
