# Generated by Django 4.1.10 on 2023-09-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_email_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
