# Generated by Django 4.1.10 on 2023-09-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='creator',
        ),
    ]
